### ISSUE TITLE
When I check "checkbox text"

### ISSUE THREAD

**Issue by severick** [cbush06/kosher#17]
When trying to use steps to click a checkbox, you should be able to use the text of the checkbox, however, it fails with the message "field is of type [%S] but must be type [checkbox]%!(EXTRA string = label)

**To Reproduce**
1. When I check "Checkbox Text"

**Expected behavior**
Should check the checkbox

![Untitled](https://user-images.githubusercontent.com/5041356/54454171-40efc080-472f-11e9-9913-71cc37c51c94.png)

**Comment by cbush06** [comment]
Appears this issue is because the checkboxes on the screen are actually icons. The actual checkboxes are invisible but are tied to a <LABEL></LABEL> element that is shown on the screen as the checkbox icons and their associated text. 

Kosher is ignoring the actual checkbox because it is invisible, hence the error. The solution would be to add a "flag" that allows testers to indicate in the selector that kosher should include invisible elements for that particular step's selector.

**Comment by cbush06** [comment]
I will add the ability to specify flags via `@{some flag}` syntax. 

In this case: `@{INVISIBLE}` or `@{invisible}`
